### ISSUE TITLE
Peer-to-Peer code review by Team 78 - The Hummingbirds 🐦

### ISSUE THREAD

**Issue by voscarmv** [elmejdki/Enumerable#2]
- Good use of `===` for class comparison 
- Check `#my_select` and `#my_map` 
- Check range input for methods
- Use `#make_array` on `#my_each` so it applies to all the methods that use it
- Really good project, mostly the implementation of `case` where no block/no parameter given
- Good project, neat and clean code. Really easy to understand.
- Good job. Nice way to put the conditions at different steps. A bit more comments would help maybe.

**Comment by elmejdki** [comment]
thank you guys for your review
