### ISSUE TITLE
Peer to peer code review Pugs - 67

### ISSUE THREAD

**Issue by fivan18** [elmejdki/Enumerable#3]
## It could be helpful to add other test cases with a range in `#my_select`.
https://github.com/elmejdki/Enumerable/blob/df12ac70bee7a098e8398cc27fd72bfbf0cbf3af/spec/enumerable_spec.rb#L47-L57

For example:

```
(1..10).my_select { |i|  i % 3 == 0 }   #=> [3, 6, 9]
```

**Comment by elmejdki** [comment]
thank you guys for your review :)
